### ISSUE TITLE
feat: Create top portion of the "Projects" page

### ISSUE THREAD

**Issue by Killianbeast** [ttugdsc/ttugdsc#12]
**Description:** Create the top portion of the "Projects" page based on the wireframe. This portion contains the DSC mission tab, the TTU GDSC Mission paragraph, and the "_Become a Member!_" button

**Reasoning:** The Projects page is empty at the moment

**Comment by Guysnacho** [comment]
GO FOR IT!!!!! I recommend checking out @jaxcksn 's documentation on how our normalized styling is set up but other than that, go crazy with it :) Thanks for participating!

**Comment by Killianbeast** [comment]
> 
> 
> GO FOR IT!!!!! I recommend checking out @jaxcksn 's documentation on how our normalized styling is set up but other than that, go crazy with it :) Thanks for participating!

Awesome, I will get to work on this as soon as I can
