### ISSUE TITLE
feat: create essential css styling

### ISSUE THREAD

**Issue by jaxcksn** [ttugdsc/ttugdsc#8]
Description: Creating a _base.scss file with Normalize (or whatever CSS reset framework works best) then adding more modules to create default styling for the entire website.

If the feature is approved I plan on establishing a 12 column grid system very similar to bootstrap, except it's done with CSS grid which gives more flexibility in the future. It would end up looking something like:
```html
<div class="container">
    <div class="row">
       <div class="col-6">
           <p>This takes up the other half of the row</p>
       </div>
       <div class="col-6">
           <p>This takes up the other half of the row</p>
       </div>
    </div>
</div>
```

Reasoning: Modern websites are responsive and it's contents should resize and move based on screen width. Having consistent styling across every page and element is also necessary.

**Comment by Guysnacho** [comment]
I really like this idea. How would you programmatically choose that though with vue? Or would we just check the viewport size IN the css file and apply styling accordingly? My bad, I don't have much experience with the implementation.

**Comment by jaxcksn** [comment]
It would all done in CSS with media queries. At certain screen widths the columns would essentially collapse into 1 single column.

**Comment by Guysnacho** [comment]
Then that's perfect, we actually some responsivity problems with the navigation bar too currently so I'm glad you want to tackle it. Go off!
