### ISSUE TITLE
[Bug] Links still cause full rerender/reload

### ISSUE THREAD

**Issue by Guysnacho** [ttugdsc/ttugdsc#9]
**Describe the bug**
When we clicking a link on in the navigation bar, the page reloads when it should be near instant (without blinking or loading)

**To Reproduce**
1. Build project (clone, `yarn`, `gridsome develop`)
2. Navigate to projects page from navbar
3. Navigate back home
4. See images reload

**Expected behavior**
Pages should be preloaded so there shouldn't be any blinking or at least it should be near instant

**Screenshots**
![Example of responsivity but with images loading](https://cdn.discordapp.com/attachments/773964321394917416/883912503359320114/progress-2.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
Because we're using Gridsome there's some specifics like the <g-link> tag that you can read about [here](https://gridsome.org/docs/linking/)

**Comment by Guysnacho** [comment]
I've blocked this one until #8 is finished since it was found during it.

**Comment by jaxcksn** [comment]
I actually have an update on this. I had the images on the homepage wrapped in a `<g-image>` tag based on the gridsome documentation, however the images don't appear to reload when I use an `<img>` tag instead. I think `<g-image>` is doing lazy loading on the image, which is what gives it the appearance of a full reload instead of it actually refreshing the window.

**Comment by Guysnacho** [comment]
Ah, okay that's a relief. So then should we just use normal `<img>` tags moving forward?

**Comment by jaxcksn** [comment]
I'm thinking that we should actually stick with `<g-image>` for now. In a production environment, the image would be local to the page, and then lazy loading would work as intended without the visual artifact. From my testing, `<g-image>` works much better for images that are local, while the `<img>`  tag works better for an image that is fetched from somewhere else.

**Comment by Guysnacho** [comment]
I see, well that's fine then. I thought there were some more things we had to do under the hood before we were ready to go. Thanks for looking into it!
